"""Register httk-atomistic's vendored entry-type and property schemas."""

from httk.core.register import register_entry_type_definition, register_property_definition

register_entry_type_definition(
    definition_id="https://schemas.optimade.org/defs/v1.3/entrytypes/optimade/structures",
    resource="httk.registry.schemas.atomistic:structures.json",
)
register_entry_type_definition(
    definition_id="https://schemas.optimade.org/defs/v1.3/entrytypes/optimade/trajectories",
    resource="httk.registry.schemas.atomistic:trajectories.json",
)

register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/symmetry/affine_transformation",
    resource="httk.registry.schemas.atomistic:affine_transformation.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/spacegroups/centring_type",
    resource="httk.registry.schemas.atomistic:centring_type.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/pointgroups/crystal_system",
    resource="httk.registry.schemas.atomistic:crystal_system.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/core/fractional_coordinate_precision",
    resource="httk.registry.schemas.atomistic:fractional_coordinate_precision.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/chemistry/species_charges",
    resource="httk.registry.schemas.atomistic:species_charges.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/chemistry/species_labels",
    resource="httk.registry.schemas.atomistic:species_labels.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/chemistry/species_spins",
    resource="httk.registry.schemas.atomistic:species_spins.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/chemistry/structure_charge",
    resource="httk.registry.schemas.atomistic:structure_charge.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/spacegroups/hall_entry",
    resource="httk.registry.schemas.atomistic:hall_entry.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/spacegroups/is_reference_setting",
    resource="httk.registry.schemas.atomistic:is_reference_setting.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/core/length_precision",
    resource="httk.registry.schemas.atomistic:length_precision.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/spacegroups/setting_it_nc",
    resource="httk.registry.schemas.atomistic:setting_it_nc.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/magnetism/site_moments",
    resource="httk.registry.schemas.atomistic:site_moments.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/trajectories/frame_stresses",
    resource="httk.registry.schemas.atomistic:frame_stresses.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/trajectories/frame_temperatures",
    resource="httk.registry.schemas.atomistic:frame_temperatures.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/trajectories/frame_total_energies",
    resource="httk.registry.schemas.atomistic:frame_total_energies.json",
)
register_property_definition(
    definition_id="https://schemas.httk.org/defs/v0.1/properties/trajectories/time_step",
    resource="httk.registry.schemas.atomistic:time_step.json",
)
