"""Private exact helpers for finite rational translation groups."""

from collections.abc import Iterable
from typing import Any

from httk.core import FracVector


def finite_translation_cosets(generators: Iterable[Any]) -> tuple[FracVector, ...]:
    """Return the subgroup of ``(Q/Z)^3`` generated by ``generators``.

    The closure is finite because every generator is rational. Results are normalized
    component-wise into ``[0, 1)`` and sorted lexicographically, which puts the zero
    translation first.
    """
    zero = FracVector((0, 0, 0))
    normalized: list[FracVector] = []
    for value in generators:
        generator = FracVector(value)
        if generator.dim != (3,):
            raise ValueError(f"a lattice translation generator must have 3 elements, got {generator.dim}")
        generator = generator.normalize()
        if generator != zero:
            normalized.append(generator)

    if not normalized:
        return (zero,)

    found = {zero}
    frontier = [zero]
    while frontier:
        current = frontier.pop()
        for generator in normalized:
            candidate = (current + generator).normalize()
            if candidate not in found:
                found.add(candidate)
                frontier.append(candidate)
    return tuple(sorted(found, key=lambda vector: tuple(vector.to_fractions())))
