[site]
slug = "httk-atomistic"
repository-url = "https://github.com/httk/httk-atomistic"
main-branch = "main"
import-roots = ["httk/atomistic", "httk/handlers"]

[[internal-dependency]]
distribution = "httk-core"
slug = "httk-core"
repository-url = "https://github.com/httk/httk-core"
main-branch = "main"
